config/routes.rb
Rails.application.routes.draw do
  resources :acta
  get 'home/about'
  root 'home#index'
  get 'home/graphics'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/actum.rb
class Actum < ApplicationRecord
    validates :dominio, :tipo_vehiculo, presence: true
    #agregar el resto de las validaciones
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/acta_controller.rb
class ActaController < ApplicationController
  before_action :set_actum, only: %i[ show edit update destroy ]

  # GET /acta or /acta.json
  def index
    @acta = Actum.all
    @articulo = Actum.group(:articulo).count
  end

  # GET /acta/1 or /acta/1.json
  def show
  end

  # GET /acta/new
  def new
    @actum = Actum.new
  end

  # GET /acta/1/edit
  def edit
  end

  # POST /acta or /acta.json
  def create
    @actum = Actum.new(actum_params)

    respond_to do |format|
      if @actum.save
        format.html { redirect_to @actum, notice: "Actum was successfully created." }
        format.json { render :show, status: :created, location: @actum }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @actum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /acta/1 or /acta/1.json
  def update
    respond_to do |format|
      if @actum.update(actum_params)
        format.html { redirect_to @actum, notice: "Actum was successfully updated." }
        format.json { render :show, status: :ok, location: @actum }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @actum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /acta/1 or /acta/1.json
  def destroy
    @actum.destroy
    respond_to do |format|
      format.html { redirect_to acta_url, notice: "Actum was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_actum
      @actum = Actum.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def actum_params
      params.require(:actum).permit(:num_acta, :dominio, :fecha, :tipo_vehiculo, :pertenece_a, :juzgado, :articulo, :autoridad)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def about
  end
end

app/helpers/acta_helper.rb
module ActaHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/acta/_form.html.erb
<%= form_with(model: actum) do |form| %>
  <% if actum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(actum.errors.count, "error") %> prohibited this actum from being saved:</h2>

      <ul>
        <% actum.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Fecha %>
    <%= form.datetime_select :fecha, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.number_field :num_acta, class:"form-control", placeholder:"Numero de acta" %>
  </div>

  <div class="field">
    <%= form.text_field :dominio, class:"form-control", placeholder:"Dominio" %>
  </div>


  <div class="field">
      <!-- <%= form.text_field :tipo_vehiculo, class:"form-control", placeholder:"Tipo de Vehiculo" %> -->
    <select class="form-select text-muted" <%= form.text_field :tipo_vehiculo %>>
      <option selected>Tipo de Vehiculo</option>
      <option value="Moto">Moto</option>
      <option value="Auto">Auto</option>
      <option value="Camioneta">Camioneta</option>
      <option value="T. Pasajeros">T. Pasajeros</option>
      <option value="Camion">Camion</option>
      <option value="Acoplado">Acoplado</option>
      <option value="Trailer">Trailer</option>
      <option value="Otro">Otro</option>    
    </select>

  </div>

  <div class="field">
    <%= form.text_field :pertenece_a, class:"form-control", placeholder:"Hecha por la base" %>
  </div>

  <div class="field">
    <%= form.text_field :juzgado, class:"form-control", placeholder:"Juzgado Perteneciente" %>
  </div>

  <div class="field">
    <!-- <%= form.text_field :articulo, class:"form-control", placeholder:"Articulo" %> -->
    <select class="form-select text-muted" <%= form.text_field :articulo %>>
      <option selected>Articulo</option>
      <option value="2">Articulo 2 - No posee la edad reglamentaria</option>
      <option value="12">Articulo 12 - </option>
      <option value="13">Articulo 13 - </option>
      <option value="14">Articulo 14 - Excede limites de contaminacion</option>
      <option value="16">Articulo 16 - No exhibir documentacion exigible</option>
      <option value="17">Articulo 17 - Los conductores que no circulen con cuidado y prevencion</option>
      <option value="18.a.1">Articulo 18.a.1 - Estando legalmente inhabilitado para circular</option>
      <option value="18.a.2">Articulo 18.a.2 - Sin haber sido habilitado para circular</option>
      <option value="18.a.3">Articulo 18.a.3 - Teniendo suspendida la habilitacion para circular</option>
      <option value="18.a.4">Articulo 18.a.4 - Sin estar habilitado para conducir ese vehiculo</option>
      <option value="18.a.5">Articulo 18.a.5 - Con habilitacion vencida</option>
      <option value="18.a.6">Ar   ticulo 18.a.6 - Sin portar su licencia habilitante</option>
      <option value="18.b">Articulo 18.b - Cedula de identificacion de vehiculo vencida</option>
      <option value="18.c.1">Articulo 18.c.1 - Sin portar el comprobante de seguro</option>
      <option value="18.c.2">Articulo 18.c.2 - Sin tener cobertura de seguro</option>
      <option value="18.d.1">Articulo 18.d.1 - Sin portar las placa de identificacion de dominio</option>
      <option value="18.d.2">Articulo 18.d.2 - Con placas de identificacion de dominio no correspondientes</option>
      <option value="18.d.3">Articulo 18.d.3 - Faltando la placa de identificacion de dominio delantera</option>
      <option value="18.d.4">Articulo 18.d.4 - Faltando la placa de identificacion de dominio trasera</option>
      <option value="18.f">Articulo 18.f - Sin portar matafuegos y balizas portatiles</option>
      <option value="18.g">Articulo 18.g - Sin que el num de acupantes guarde relacion con la capacidad del vehiculo</option>
      <option value="18.i">Articulo 18.i - Por no poseer los sistemas de seguridad originales en buen estado</option>
      <option value="18.j.1">Articulo 18.j.1 - En moto, circular sin casco</option>
      <option value="18.j.2">Articulo 18.j.2 - en moto, sin parabrisas el conductor que no use anteojos de seguridad</option>
      <option value="18.k">Articulo 18.k - Por no usar los correajes de seguridad</option>
      <option value="19">Articulo 19 - No ceder el paso / no respetar prioridades / no retroceder</option>
      <option value="20">Articulo 20 - Por adelantarse por la derecha</option>
      <option value="21">Articulo 21 - Por no respetar la senalizacion</option>
      <option value="22.a">Articulo 22.a - No respetar las luces de los semaforos / no detenerse en la lina marcada</option>
      <option value="22.e">Articulo 22.b - Por obstruir el transito de la via transversal</option>
      <option value="22.f">Articulo 22.f - Por girar a la izquierda en vias de doble mano</option>
      <option value="23">Articulo 23 - No ajustarse a las reglas de circulacion establecidas para las vias multicarriles</option>
      <option value="24">Articulo 24 - No ajustarse a las reglas de circulacion establecidas para las autopistas</option>
      <option value="25">Articulo 25 - Por no observas las lineas previstas para el uso de las luces</option>
      <option value="26">Articulo 26 - Por circular, detenerse en infraccion a las prohibiciones en la via publica</option>
      <option value="27">Articulo 27 - Por no obsevar las reglas de estacionamiento</option>
      <option value="28">Articulo 28 - No respetar los limites de velocidad</option>
      <option value="30">Articulo 30 - Por transportar escolares o menores (14) en infraccion a las normas</option>
      <option value="32">Articulo 32 - Por circular con vehiculo de emergencia en infraccion a las normas</option>
      <option value="33">Articulo 33 - Por circular con maquinaria especial en infraccion a las normas</option>
      <option value="34">Articulo 34 - Por utilizar franquicia de transito no reglamentaria</option>
      <option value="35">Articulo 35 - Por no cumplir con obligaciones legales para participes de un accidente</option>
      <option value="36">Articulo 36 - Por negarse a realizar la prueba de alcoholemia</option>
      <option value="38.c">Articulo 38.c - Las que afecten por contaminacion al medio ambiente</option>
      <option value="38.g">Articulo 38.g - Fugar o negarse a suministrar documentacion</option>
      <option value="38.m">Articulo 38.m - la conduccion en estado de intoxicacion alcoholica</option>
      <option value="38.o">Articulo 38.o - La conduccion a una distancia menor a la prudente al vehiculo que lo precede</option>
      <option value="38.r">Articulo 38.r - La conduccion de vehiculos utilizando auriculares/comunicacion manual/pantallas</option>
      <option value="38.s">Articulo 38.s - La conduccion de vehiculos propulsados por el conductor, traccion a sangre y maquinaria especial</option>
      <option value="38.x">Articulo 38.x - La conduccion de vehiculos a contramano</option>
      <option value="39">Articulo 39 - Por circular sin haber realizado RTO</option>
      <option value="39">Articulo 39 - Por circular sin la documentacion que acredite la RTO</option>
      <option value="40">Articulo 40 - Por circular sin casco los acompanantes de motos</option>
    </select>
  </div>

  <div class="field">
    <%= form.text_field :autoridad, class:"form-control", placeholder:"Autoridad / Agente" %>
  </div>

  <div class="form-check form-switch">
    <input class="form-check-input" type="checkbox" id="flexSwitchCheckChecked" checked>
    <label class="form-check-label" for="flexSwitchCheckChecked">Checked switch checkbox input</label>
  </div>

  <div class="actions">
    <%= form.submit %>
 </div>
<% end %>

app/views/acta/edit.html.erb
<h1>Editing Actum</h1>

<%= render 'form', actum: @actum %>

<%= link_to 'Show', @actum %> |
<%= link_to 'Back', acta_path %>

app/views/acta/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Acta</h1>

<table class="table table-striped table-hover"> 
  <thead class="table-primary">
    <tr class="text-center">
      <th>Num acta</th>
      <th>Dominio</th>
      <th>Fecha</th>
      <th>Tipo vehiculo</th>
      <th>Pertenece a</th>
      <th>Juzgado</th>
      <th>Articulo</th>
      <th>Autoridad</th>
    </tr>
  </thead>

  <tbody>
    <% @acta.each do |actum| %>
      <tr class="text-justify">
        <td>
          <%= link_to actum.num_acta, actum %>
        </td>
        <td><%= actum.dominio %></td>
        <td><%= actum.fecha %></td>
        <td><%= actum.tipo_vehiculo %></td>
        <td><%= actum.pertenece_a %></td>
        <td><%= actum.juzgado %></td>
        <td><%= actum.articulo %></td>
        <td><%= actum.autoridad %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Actum', new_actum_path %>

app/views/acta/new.html.erb
<h1 class=>Nueva Acta</h1>

<%= render 'form', actum: @actum %>

<%= link_to 'Back', acta_path %>

app/views/acta/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Num acta:</strong>
  <%= @actum.num_acta %>
</p>

<p>
  <strong>Dominio:</strong>
  <%= @actum.dominio %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @actum.fecha %>
</p>

<p>
  <strong>Tipo vehiculo:</strong>
  <%= @actum.tipo_vehiculo %>
</p>

<p>
  <strong>Pertenece a:</strong>
  <%= @actum.pertenece_a %>
</p>

<p>
  <strong>Juzgado:</strong>
  <%= @actum.juzgado %>
</p>

<p>
  <strong>Articulo:</strong>
  <%= @actum.articulo %>
</p>

<p>
  <strong>Autoridad:</strong>
  <%= @actum.autoridad %>
</p>

<%= link_to 'Edit', edit_actum_path(@actum) %> |
<%= link_to 'Back', acta_path %> |
<%= link_to 'Destroy', @actum, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
		<%= link_to 'Seguridad Vial', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
       
      </ul>
      
    </div>
  </div>
</nav>

app/views/home/graphics.html.erb
<h3 class=text-center> Por Articulo </h3>
<%= pie_chart Actum.group(:articulo).count %>

<h3 class=text-center> Por Base </h3>
<%= column_chart Actum.group(:pertenece_a).count %>

app/views/home/index.html.erb
<h3 class="container">Oficina de Legales - DCCyFV</h3>

<br/>
<br/>

<div class="container">
	<div class="row justify-content-between">
		<div class="col-4">
			<%= link_to 'Cargar Acta', new_actum_path, class:'btn btn-primary text-white' %>
		</div>
		<div class="col-4">
			<%= link_to 'Lista', acta_path, class:'btn btn-primary text-white' %>
		</div>
		<div class="col-4">
			<%= link_to 'Estadisticas', home_graphics_path ,class:'btn btn-primary text-white' %>
		</div>

	</div>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <title>Legales App</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <body>

    <%= render 'home/header' %>
    <div class="container">
      <br/>
      <%= yield %>
    <div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
    -->
  </body>
</html>